⁷## -*- coding: utf-8 -*-
"""ColabPython-01610281.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zndqnz3ocgMtdA2m6WIXM3dED0raGbH7
"""

print ("Olá Uninassau!")

numero = int (input('Digite o número: '))

print (f" toma teu {numero} de volta !!")

numero = int (input("Digite o primeiro número: "))
numero2 = int (input("Digite o segundo número: "))

soma = numero + numero2

print (f"Seu resultado foi de: {soma}")

nota1 = int (input("Digite a primeira nota: "))
nota2 = int (input("Digite a segunda nota: "))
nota3 = int (input("Digite a terceira nota: "))
nota4 = int (input("Digite a quarta nota: "))

media = (nota1+nota2+nota3+nota4)/4

print (f"Sua media foi de : {media:.2f}")

if media < 7:
  print (f"Você foi reprovado!")

else:

  print (f"Você foi aprovado!")

metros = int (input("Digite o valor em metros: "))
centimetro = (metros)*100
print(f"O seu valor em centimetros é de: {centimetro}cm")

import math

raio = int (input("Digite o raio: "))
area = math.pi*(raio**2)
print(f"Sua area é de: {area:.2f}")

lado= int (input("Qual o tamanho do lado do quadrado?: "))
area= (lado**2)
print(f"A sua área é de: {area}")
print(f"E o dobro da sua área é de: {area*2}")

hora= int (input("Quantas horas você trabalha por mês?: "))
ganho= int (input("Quanto você ganha por hora?: "))
salario= (hora)*(ganho)
print (f"Você ganha por mês: {salario}")

valor= int(input("Digite um valor: "))

if valor>0:
  print(f"Seu valor é positivo")
elif valor==0:
  print(f"Seu valor é neutro")
else:
 print (f"Seu valor é negativo")

sexo= str(input("Digite seu sexo(F/M): "))

if sexo== "F" or sexo== "f":
  print(f"Você é uma mulher")
elif sexo== "M" or sexo== "m":
  print(f"Você é um homem")
else:
 print("Sexo invalido")